spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka
  instance:
    prefer-ip-address: true


